AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Metrics/MethodLength:
  Max: 35
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 25
