inherit_from: ../.rubocop.yml

Style/BlockDelimiters:
  EnforcedStyle: semantic

Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
